# Generated by Django 5.2.1 on 2025-11-05 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='business_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('business_name', models.CharField(max_length=255, verbose_name='business name')),
                ('whatsapp_number', models.CharField(max_length=20, verbose_name='whatsapp number')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/', verbose_name='logo')),
                ('business_details', models.TextField(blank=True, null=True, verbose_name='business details')),
                ('stripe_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_connected', models.BooleanField(default=False)),
                ('stripe_connection_date', models.DateTimeField(blank=True, null=True)),
                ('stripe_details_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'business profile',
                'verbose_name_plural': 'business profiles',
                'ordering': ['business_name'],
            },
        ),
    ]
