# Generated by Django 5.2.1 on 2025-11-05 05:06

import django.core.validators
import django.db.models.deletion
import quoteapp.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('folder_id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'folder',
                'verbose_name_plural': 'folders',
                'ordering': ['folder_name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('voice', 'Voice')], default='manual', max_length=10)),
                ('payment_speed', models.CharField(choices=[('standard', 'Standard Payment'), ('faster', 'Faster Payment')], default='standard', help_text='Payment processing speed option', max_length=20)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='discount amount')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=10, verbose_name='discount type')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='subtotal')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='VAT rate')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total')),
                ('quote_status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('won', 'Won'), ('lost', 'Lost')], default='unpaid', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='unpaid', max_length=20)),
                ('sent_via', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('both', 'Both'), ('none', 'None')], default='none', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('issue_date', models.DateField(verbose_name='issue date')),
                ('due_date', models.DateField(verbose_name='due date')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='paid date')),
                ('signature', models.ImageField(blank=True, null=True, upload_to=quoteapp.models.invoice_signature_upload_path)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=quoteapp.models.invoice_pdf_upload_path)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to=quoteapp.models.invoice_pdf_upload_path)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to=quoteapp.models.invoice_pdf_upload_path)),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('can_edit', models.BooleanField(default=True)),
                ('payment_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='clientapp.client')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='quoteapp.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(blank=True, max_length=500, null=True)),
                ('quote_description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('service_duration', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('service_type', models.CharField(default='General Service', max_length=255, verbose_name='service name')),
                ('service_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_unit', models.CharField(choices=[('days', 'Days'), ('hours', 'Hours')], default='hours', max_length=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quoteapp.invoice')),
            ],
            options={
                'db_table': 'invoice_items',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('quote_id', models.AutoField(primary_key=True, serialize=False)),
                ('quote_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('voice', 'Voice')], default='manual', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='discount amount')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=10, verbose_name='discount type')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='VAT rate')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
                ('issue_date', models.DateField(verbose_name='issue date')),
                ('due_date', models.DateField(verbose_name='due date')),
                ('quote_status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('won', 'Won'), ('lost', 'Lost')], default='draft', max_length=20)),
                ('sent_via', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('both', 'Both'), ('none', 'None')], default='none', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to=quoteapp.models.quote_signature_upload_path)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=quoteapp.models.quote_pdf_upload_path, verbose_name='PDF file')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to=quoteapp.models.quote_pdf_upload_path)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to=quoteapp.models.quote_pdf_upload_path)),
                ('service_location', models.CharField(blank=True, help_text='Leave blank to use client address', max_length=255, null=True, verbose_name='service location')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('can_edit', models.BooleanField(default=True)),
                ('accept_link', models.URLField(blank=True, null=True)),
                ('reject_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='clientapp.client')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='quoteapp.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='quoteapp.quote'),
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_description', models.TextField()),
                ('material_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('service_type', models.CharField(default='General Service', max_length=255, verbose_name='service name')),
                ('service_duration', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('duration_unit', models.CharField(choices=[('days', 'Days'), ('hours', 'Hours')], default='hours', max_length=10)),
                ('service_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quoteapp.quote')),
            ],
            options={
                'db_table': 'quote_items',
            },
        ),
        migrations.CreateModel(
            name='QuoteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='quoteapp.quote')),
            ],
            options={
                'db_table': 'quote_tokens',
            },
        ),
        migrations.CreateModel(
            name='ScannedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=quoteapp.models.scanned_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_docs', to='clientapp.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scanned_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('user', 'folder_name'), name='unique_folder_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['user', 'quote_status'], name='quotes_user_id_c90e59_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['client'], name='quotes_client__74c431_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['created_at'], name='quotes_created_c74d71_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['user', 'is_deleted'], name='quotes_user_id_a41000_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', 'quote_status'], name='invoices_user_id_4f8c48_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client'], name='invoices_client__a0059b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['created_at'], name='invoices_created_bfa8ab_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='invoices_invoice_7778bc_idx'),
        ),
    ]
