# Generated by Django 5.2.1 on 2025-11-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='duration_unit',
            field=models.CharField(choices=[('days', 'Days'), ('hours', 'Hours')], default='hours', max_length=10),
        ),
    ]
