# Generated by Django 5.2.1 on 2025-11-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0003_quotecounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
