# Generated by Django 5.2.1 on 2025-12-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0004_alter_quote_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='duration_unit',
            field=models.CharField(choices=[('days', 'Days'), ('hours', 'Hours')], default='hours', max_length=10),
        ),
    ]
