# Generated by Django 5.2.1 on 2025-12-17 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0006_invoicecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanneddocument',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scanned_images', to='quoteapp.folder'),
        ),
    ]
