# Generated by Django 5.2.1 on 2025-12-18 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0002_initial'),
        ('quoteapp', '0007_scanneddocument_folder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanneddocument',
            name='folder',
        ),
        migrations.AlterField(
            model_name='scanneddocument',
            name='client',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scanned_docs', to='clientapp.client'),
        ),
        migrations.AlterField(
            model_name='scanneddocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
