# Generated by Django 5.2.1 on 2025-12-18 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0008_remove_scanneddocument_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanneddocument',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scanned_images', to='quoteapp.folder'),
        ),
    ]
