# Generated by Django 5.2.1 on 2025-12-18 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0002_initial'),
        ('quoteapp', '0009_scanneddocument_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanneddocument',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scanned_docs', to='clientapp.client'),
        ),
    ]
