# Generated by Django 5.2.1 on 2026-02-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0010_alter_scanneddocument_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='account_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sort_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
