# Generated by Django 5.2.1 on 2025-11-05 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientapp', '0001_initial'),
        ('quoteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservice',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_services', to='quoteapp.quote'),
        ),
    ]
