# serializers.py
from rest_framework import serializers
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.utils import timezone
from datetime import timedelta
import random
import string
from .models import OTP
from .utils import validate_and_get_otp
from django.conf import settings

User = get_user_model()

class SignupSerializer(serializers.Serializer):
    email = serializers.EmailField()
    # name = serializers.CharField(max_length=150)
    password = serializers.CharField(write_only=True, min_length=8)
    referral_code = serializers.CharField(max_length=20, required=False, allow_blank=True)
    
    def validate_email(self, value):
        value = value.lower().strip()#makes email lowercase and removes spaces.
        verified_user = User.objects.filter(email=value, verified=True).exists()#.filter() returns a QuerySet, not a True/False value.
        #.exists() is used to check if any record matches (returns True or False).

        if verified_user:
            raise serializers.ValidationError("This email is already registered.")
        return value
    
    # def validate_name(self, value):
    #     return value.strip()
    
    def create(self, validated_data):
        email = validated_data['email']
        
        # It removes old unverified accounts with the same email before creating a new one.
        User.objects.filter(email=email, verified=False).delete()
        
        # Create new user
        user = User.objects.create_user(
            username=email,
            email=email,
            # first_name=validated_data['name'],
            password=validated_data['password'],
            referral_code=validated_data.get('referral_code') or None,
            verified=False
        )
        referral_code_input = validated_data.get('referral_code')
        if referral_code_input:
            try:
                ref_code_obj = ReferralCode.objects.get(code=referral_code_input)
                ReferralUse.objects.create(referral_code=ref_code_obj, used_by=user)
                ref_code_obj.trial_days_earned += 30
                ref_code_obj.save()
                # Optionally: extend owner's trial on your User/subscription model here
            except ReferralCode.DoesNotExist:
                pass  # invalid code, just ignore silently
        # Generate and send OTP
        otp_code = ''.join(random.choices(string.digits, k=6))
        '''
        Generates a 6-digit random OTP made of numbers.
        string.digits = '0123456789'
        random.choices(..., k=6) → picks 6 random digits.
        .join(...) → combines them into a single string like '483920'.
        '''
        expires_at = timezone.now() + timedelta(minutes=10)

        #Deletes any previous unused OTPs for that email before sending a new on
        OTP.objects.filter(email=email, is_used=False).delete()
        OTP.objects.create(
            email=email,
            otp_code=otp_code,
            expires_at=expires_at
        )
        
        self.send_otp_email(email, otp_code)
        
        return user
    '''
    ❓From where this 'validated_data' comes in the line def create(self, validated_data)?
    Ans:
    When DRF serializer’s .is_valid() runs successfully, it stores cleaned input data in validated_data.
    DRF automatically passes this dictionary into the create() method when .save() is called.
    👉 In short: validated_data = all the valid fields from the user’s request (after passing validation).
    
    '''


    '''
    ❓Why @staticmethod for send_otp_email?
    Ans:
    @staticmethod: Means the method doesn't need access to self (the serializer instance),or any instance data. It's a utility function that can work independently
    Use case: The method only uses the parameters passed to it (email and otp_code)

    ❓why I can use a independant function like send_otp_email in this case

    🔴email and otp_code are generated by your system inside the create() method — not sent by the user.
    🔴Since send_otp_email() just uses those values to send an email, it doesn’t need anything from the serializer instance (self).
    🔴That’s why it can be a @staticmethod — it works independently of the serializer object.
    '''
    @staticmethod
    def send_otp_email(email, otp_code):
        subject = "Your OTP Code for Verification in Fixa"
        message = f"""Dear User,

        Thank you for registering with Fixa.

        Please use the One-Time Password (OTP) below to verify your email address:

        OTP Code: {otp_code}

        This code is valid for 10 minutes. For your security, please do not share this code with anyone.

        If you did not request this, please ignore this email.

        Best regards,  
        Fixxa Support Team
        """
        #send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, [email])
        send_mail(
            subject,
            message,
            settings.DEFAULT_FROM_EMAIL,
            [email],
            fail_silently=False
        )


class VerifyOTPSerializer(serializers.Serializer):
    email = serializers.EmailField()
    otp_code = serializers.CharField(max_length=6)
    
    def validate(self, data):
        email = data['email'].lower().strip()
        otp_code = data['otp_code'].strip()
        
        # try:
        #     otp = OTP.objects.filter(email=email, is_used=False).latest('created_at')
        # except OTP.DoesNotExist:
        #     raise serializers.ValidationError("No valid OTP found for this email.")
        
        # if not otp.is_valid():
        #     raise serializers.ValidationError("OTP has expired.")
        
        # if otp.otp_code != otp_code:
        #     raise serializers.ValidationError("Invalid OTP code.")
        otp = validate_and_get_otp(email, otp_code)  # 👈 call the function here

        data['otp'] = otp
        return data


class ResendOTPSerializer(serializers.Serializer):
    email = serializers.EmailField()
    
    def validate_email(self, value):
        value = value.lower().strip()
        user = User.objects.filter(email=value, verified=False).exists()
        if not user:
            raise serializers.ValidationError("No pending verification for this email.")
        return value


class LoginSerializer(serializers.Serializer):
    email = serializers.EmailField()
    password = serializers.CharField(write_only=True)
    
    def validate(self, data):
        email = data['email'].lower().strip()
        password = data['password']
        
        try:
            user = User.objects.get(email=email, verified=True)
        except User.DoesNotExist:
            raise serializers.ValidationError("Invalid email")
        
        if not user.check_password(password):#if the password enterd by the user is not correct 
            raise serializers.ValidationError("Invalid password.")
        
        data['user'] = user
        return data


class ForgotPasswordSerializer(serializers.Serializer):
    email = serializers.EmailField()
    
    def validate_email(self, value):
        value = value.lower().strip()
        user = User.objects.filter(email=value, verified=True).exists()
        if not user:
            raise serializers.ValidationError("Email not found or not verified.")
        return value


class ResetPasswordSerializer(serializers.Serializer):
    # email = serializers.EmailField()
    # otp_code = serializers.CharField(max_length=6)
    new_password = serializers.CharField(write_only=True, min_length=8)
    
    # def validate(self, data):
    #     email = data['email'].lower().strip()
    #     otp_code = data['otp_code'].strip()
        
    #     # try:
    #     #     otp = OTP.objects.filter(email=email, is_used=False).latest('created_at')
    #     # except OTP.DoesNotExist:
    #     #     raise serializers.ValidationError("No valid OTP found for this email.")
        
    #     # if not otp.is_valid():
    #     #     raise serializers.ValidationError("OTP has expired.")
        
    #     # if otp.otp_code != otp_code:
    #     #     raise serializers.ValidationError("Invalid OTP code.")
    #     otp = validate_and_get_otp(email, otp_code)  # 👈 call the function here      
    #     data['otp'] = otp
    #     return data




from .models import ReferralCode, ReferralUse

class GenerateReferralCodeSerializer(serializers.Serializer):
    def generate_unique_code(self):
        while True:
            code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=8))
            if not ReferralCode.objects.filter(code=code).exists():
                return code

    def create(self, validated_data):
        user = validated_data['user']
        if hasattr(user, 'referral_code_obj'):
            return user.referral_code_obj  # already has one
        code = self.generate_unique_code()
        return ReferralCode.objects.create(owner=user, code=code)


class ReferralStatsSerializer(serializers.ModelSerializer):
    owner_id = serializers.UUIDField(source='owner.id')
    owner_name = serializers.SerializerMethodField()
    owner_email = serializers.EmailField(source='owner.email')
    total_signups = serializers.SerializerMethodField()
    signups = serializers.SerializerMethodField()

    class Meta:
        model = ReferralCode
        fields = ['code', 'owner_id', 'owner_name', 'owner_email',
                  'trial_days_earned', 'total_signups', 'signups', 'created_at']

    def get_owner_name(self, obj):
        return f"{obj.owner.first_name} {obj.owner.last_name}".strip() or obj.owner.username

    def get_total_signups(self, obj):
        return obj.uses.count()

    def get_signups(self, obj):
        return [
            {
                "user_id": str(use.used_by.id),
                "email": use.used_by.email,
                "signed_up_at": use.used_at.isoformat()
            }
            for use in obj.uses.select_related('used_by').all()
        ]













